/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const contracts = {
  999: {
    RolesAuthority: {
      address: "0x86f11a6db84635f566430e7cB0224F6C4ac6a28F",
      abi: [] as const, // Will be populated
    },
    SuperYieldVault: {
      address: "0x8851862f714f2984c3E3Bcfc9Fafb57D67dB6845",
      abi: [] as const,
    },
    YieldAccountant: {
      address: "0xf4F3b37236Dd3e0bbcDe9EAA1C6553220A30B9aE",
      abi: [] as const,
    },
    StrategyManager: {
      address: "0x4E46c6826166AAD7ed6Ca0cdFCcd46818ea602aa",
      abi: [] as const,
    },
    DepositTeller: {
      address: "0x2f245E60EE78Acb2847D8FE1336725307C7B38Df",
      abi: [] as const,
    },
  },
} as const;

export default contracts satisfies GenericContractsDeclaration;
